### ISSUE TITLE
Support 50 baud TTY

### ISSUE THREAD

**Issue by InterLinked1** [dgorski/app_tdd#12]
Instead of just 45.45 V18, there should also be support for the international 50 baud modem protocol (as an optional runtime option)

**Comment by dgorski** [comment]
I have no way to test 50bps operation but a flag has been added to enable International 50bps versus US-TTY 45.45 (flag i).

**Comment by dgorski** [comment]
@InterLinked1  -  Is there a way that you can test this?  I don't have any 50bps TTY capability.

**Comment by InterLinked1** [comment]
Not me personally, but I know someone interested in 50bps TTY and he is planning to acquire such a TTY and test it. If he updates me, I will relay it back to you.
Assuming the core logic works, and there isn't a major difference for 50bps, it might be safe to assume it works and a bug could be opened if, for some reason, it was found that it did not.
I see you updated some other stuff and those I should be able to test, and will get back to you shortly on.

**Comment by dgorski** [comment]
That's what I was thinking.  The difference is passing a _50 flag instead of a _45 flag to the underlying spandsp library, so I think it's safe to assume that if sapndsp can do 50bps properly as it advertises then this should work fine.
