### ISSUE TITLE
Messages consisting of whitespace are not transmitted

### ISSUE THREAD

**Issue by InterLinked1** [dgorski/app_tdd#3]
It appears when using the TddTx Manager action, if a message consists solely of whitespace, it is never sent onto the channel.

If there are other characters in the message, then the whitespace is there.

Not sure where exactly the problem lies, but since I am sending an AMI event for each character from the relay operator to the TTY caller, the result is that no whitespace is ever sent to the TTY.

A workaround I have found in my application is, before sending the AMI event, replace " " with "_" since underscores are treated as spaces. Just thought I'd let you know though.

**Comment by dgorski** [comment]
I believe this is a problem with AMI, in that AMI "cleanses" the input (stripping leading and trailing whitespace).  The TDD code transmits whatever AMI passes along, there no way to know if AMI altered the original payload before calling the TDD code.

**Comment by InterLinked1** [comment]
> I believe this is a problem with AMI, in that AMI "cleanses" the input (stripping leading and trailing whitespace). The TDD code transmits whatever AMI passes along, there no way to know if AMI altered the original payload before calling the TDD code.

Can't we escape the string, if it's just whitespace, to prevent AMI from doing that, though?
It's going from the TTY code to AMI so if there's something we can do in the tdd module to prevent that AMI "feature" from kicking in, I think it'd be worth pursuing, even if it requires an additional option, like "w" to "preserve whitespace by escaping it". Perhaps just prepend a backslash to the beginning of the string?

**Comment by InterLinked1** [comment]
Another thought... for handling the case of important whitespace being removed (such as just a single space), the space could be converted to an underscore (_).

In the TTY perspective, space is equivalent to underscore, so this would at least fix this issue and most of the pressing incidences of this edge case.
