### ISSUE TITLE
Mixed declarations and code

### ISSUE THREAD

**Issue by InterLinked1** [dgorski/app_tdd#4]
You can't do this in Asterisk, since developer mode uses C90 compilation:

```
app_tdd.c: In function ‘tdd_rx_exec’:
app_tdd.c:566:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  566 |  v18_state_t *vs = &ti->v18_state;
```

**Comment by InterLinked1** [comment]
Found a few other things as well - in addition to previous things:
<replaceable> cannot be used within <synopsis>, since synopsis can't have children.
<para> should go inside <note>, not the other way around.

Here is a diff that contains changes needed for the module to properly build (plus with a hardcoded decreased buffer threshold for now): https://github.com/InterLinked1/phreakscript/blob/master/patches/tdd.diff

Feel free to incorporate, I'll just build app_tdd with the patch until then.

**Comment by dgorski** [comment]
Yeah, I am not familiar with "developer mode", so I've never run into any of these problems.  How do you enable it, and why would you want do so?  What does it do for you?

**Comment by InterLinked1** [comment]
Developer mode enforces stricter compilation requirements., such as not allowing C99-only syntax. Gerrit/Jenkins will compile with developer mode so if you don't do it during development and there is an inconsistency, Jenkins will give your patch a -2 for verification.

So if you don't use development mode, you'll just get surprises later, basically.

In "Compiler Flags" enable the developer mode, I forget if it's the same as test framework or not. Usually I also enable the backtrace and debug on dev machines for debugging as well, but I don't think that's required.

**Comment by dgorski** [comment]
Updated to resolve xml doco and "mixed declarations and code" issues.  Also implemented options processing to allow specification of buffer length for received characters - b(x) option.  Tested on 18.8.0.

**Comment by InterLinked1** [comment]
I think bufsiz in the documentation should be bufsize, but doesn't really matter that much... just FYI.
Thanks for adding these upstream!

**Comment by InterLinked1** [comment]
Also, hold up, the b and c options aren't supposed to be required, are they? The documentation says they are, but the code (I think correctly) doesn't make them required. So another documentation thing.

**Comment by dgorski** [comment]
If you specify b() you are required to also specify a value i.e. b() is not allowed but b(3) is acceptable.  Same for c(str)

**Comment by dgorski** [comment]
to be clear, neither OPTION is required, but each requires an ARGUMENT if specified.

**Comment by InterLinked1** [comment]
Got it, that makes sense. I was mixing up parameters and options and the implications of required for each.
