### ISSUE TITLE
Need option to translate spaces to underscores

### ISSUE THREAD

**Issue by InterLinked1** [dgorski/app_tdd#8]
As previously discussed, AMI can gobble leading/trailing whitespace which can cause problems where whitespace is significant/necessary.

Something like this (maybe an option to do this, if you feel it shouldn't always be done), is needed to make this application work around that - real TTYs treat " " and "_" the same so this is the correct fix for this issue:

https://github.com/dgorski/app_tdd/blob/main/app_tdd.c#L519

```
else if(msg[i] == ' ') {
	buf[o++] = '_';
}
```

maybe `AST_APP_OPTION('s', MUXFLAG_CONVERT_SPACES)` ?

**Comment by dgorski** [comment]
This is alluded to in the "things that still need work" section of the README (received messages should be encoded as they may contain control sequences).  I don't seem to lose spaces with my AMI integration.  I'm using the AMI-over-HTTP - maybe that does a better job of retaining leading/trailing spaces?

**Comment by InterLinked1** [comment]
What happens if you send a message that consists solely of a space?
I'm using regular AMI, not HTTP, on localhost, so yeah, not sure if that makes a difference.

**Comment by dgorski** [comment]
Added option 's' to send spaces as underscores.  Tested on 18.8.0
